PencilBox/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PbData.Business;
using PbData.Entities;
using PencilBox.Helpers;
using WebMatrix.WebData;
using PencilBox.Models;
using PbData.Extensions;

namespace PencilBox.Controllers
{
    public class OrderController : Controller
    {
        //
        // GET: /Order/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New(Guid productId)
        {
            bn_Product bnProduct = new bn_Product();
            ps_Order model = new ps_Order();

            var user = ps_Membership.GetUser();
            var product = bnProduct.GetById(productId);

            if (user != null)
            {
                //add some default values.
                model.Order.UserId = user.UserId;
                model.Order.CustomerName = user.FullName;
            }

            model.Order.Price = (product.DiscountPrice.HasValue) ?
                product.DiscountPrice.Value :
                product.Price;
            model.Order.Amount = 1;
            model.Order.ProductId = productId;
            model.Product = product;

            return View(model);
        }

        [HttpPost]
        public ActionResult New(ps_Order model)
        {
            if (ModelState.IsValid)
            {
                bn_Order bnOrder = new bn_Order();
                var orderId = bnOrder.Create(
                    model.Order.ProductId,
                    model.Order.UserId,
                    model.Order.CustomerName,
                    model.Order.CustomerPhone,
                    model.Order.Price,
                    model.Order.Amount,
                    model.Order.Address,
                    model.Order.Comment);

                if (orderId != Guid.Empty)
                {
                    return RedirectToAction("Done");
                }
                else
                {
                    ViewBag.Message = "Error";
                    return View(model);
                }
            }

            return View(model);
        }

        public ActionResult Done()
        {
            return View();
        }

        [Authorize]
        public ActionResult Salesman()
        {
            bn_Order bnOrder = new bn_Order();
            var user = ps_Membership.GetUser();

            var model = bnOrder.GetBySalesman(
                user.UserId, 
                EOrder_Status.Available);

            //ESpecialTag.Discount.
            return View(model);
        }

        [Authorize]
        public ActionResult Customer()
        {
            bn_Order bnOrder = new bn_Order();
            var user = ps_Membership.GetUser();

            var model = bnOrder.GetByUserId(user.UserId);

            return View(model);
        }
    }
}

PencilBox/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PbData.Entities;
using PbData.Business;
using PbData.Extensions;
using PencilBox.Models;
using PencilBox.Helpers;

namespace PencilBox.Controllers
{
    public class ProductController : Controller
    {
        private void Photo_UpdateProductId(Guid productId, List<ps_ProductPhoto> photos)
        {
            var bnPhoto = new bn_Photo();
            foreach (var item in photos)
            {
                bnPhoto.UpdateProductId(
                    item.PhotoId,
                    productId);
            }
        }

        public ActionResult Index(Guid? tagId, string tagName = "juddy")
        {
            bn_Product bnProduct = new bn_Product();
            List<pb_Product> model = new List<pb_Product>();
            ViewBag.tagName = tagName;
            if (!tagId.HasValue)
            {
                model = bnProduct.GetByTagName(tagName, 0);
            }
            else
            {
                model = bnProduct.GetByHashTagId(tagId.Value, 0);
            }

            ViewBag.TagName = tagName;
            return View(model);
        }

        public ActionResult List(Guid? tagId, string tagName = "juddy", int page = 0)
        {
            int itemsPerPage = 36;
            if (page < 0) page = 0;

            bn_Product bnProduct = new bn_Product();
            List<pb_Product> model = new List<pb_Product>();
            int tmpPages;

            if (!tagId.HasValue)
            {
                var tmpAll = bnProduct.GetByTagName(tagName).Count;
                tmpPages = tmpAll / itemsPerPage;
                if (tmpPages * itemsPerPage < tmpAll) tmpPages++;
                tmpPages--;
                if (page > tmpPages) page = tmpPages;

                model = bnProduct.GetByTagName(tagName)
                    .Skip(page * itemsPerPage)
                    .Take(itemsPerPage).ToList();
            }
            else
            {
                var tmpAll = bnProduct.GetByHashTagId(tagId.Value).Count;
                tmpPages = tmpAll / itemsPerPage;
                if (tmpPages * itemsPerPage < tmpAll) tmpPages++;
                tmpPages--;
                if (page > tmpPages) page = tmpPages;

                bn_HashTag bnHashtag = new bn_HashTag();
                tagName = bnHashtag.GetById(tagId.Value).TagName;

                model = bnProduct.GetByHashTagId(tagId.Value)
                    .Skip(page * itemsPerPage)
                    .Take(itemsPerPage).ToList();
            }

            if (page > 0)
                ViewBag.Back = "OK";
            else
                ViewBag.Back = "Disable";

            if (page < tmpPages)
                ViewBag.Next = "OK";
            else
                ViewBag.Next = "Disable";

            ViewBag.CurrentPage = page;
            ViewBag.TagName = tagName;
            return View("Index", model);
        }

        public ActionResult Page(Guid? tagId, string tagName = "pbox", int page = 0)
        {
            bn_Product bnProduct = new bn_Product();
            List<pb_Product> model = new List<pb_Product>();

            if (!tagId.HasValue)
            {
                model = bnProduct.GetByTagName(tagName, page);
            }
            else
            {
                model = bnProduct.GetByHashTagId(tagId.Value, page);
            }

            ViewBag.TagName = tagName;
            return View(model);
        }

        public ActionResult Category(string tag, string category)
        {
            bn_Product bnProduct = new bn_Product();
            var model = bnProduct.GetByCategory(tag, category);

            ViewBag.TagName = tag;
            return View("Index", model);
        }
        
        [HttpPost]
        public ActionResult Filter(string request = "#juddy")
        {
            bn_Product bnProduct = new bn_Product();
            var model = bnProduct.GetByTags(request);

            var tags = bn_HashTag.DivTags(request);
            ViewBag.Tags = tags;
            ViewBag.FilterRequest = bn_HashTag.MergerTag(tags);

            return View(model);
        }

        [Authorize]
        public ActionResult WishList()
        {
            bn_Product bnProduct = new bn_Product();
            var model = bnProduct.GetByUserAndTagName(
                ps_Membership.GetUser().UserId,
                ESpecialTag.Favourite.ParseToText());

            ViewBag.TagName = "wish list";
            return View("Index", model);
        }

        [Authorize]
        public ActionResult Add(string tag)
        {
            ps_ProductCreate model = new ps_ProductCreate();

            model.Product = new pb_Product();
            model.ProductPhotos = new List<ps_ProductPhoto>();
            model.Tags = string.Format("#{0}", tag);

            Session["Photos"] = new List<ps_ProductPhoto>();

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(ps_ProductCreate model)
        {
            List<ps_ProductPhoto> photos = (List<ps_ProductPhoto>)Session["Photos"];
            if (ModelState.IsValid && photos.Count > 0)
            {
                var bnProduct = new bn_Product();

                var productId = bnProduct.Create(
                    ps_Membership.GetUser().UserId,
                    model.Product.Name,
                    model.Product.Price,
                    model.Product.Description);

                if (productId != null)
                {
                    var bnProductTag = new bn_ProductTag(productId);

                    //updated photos for product
                    Photo_UpdateProductId(productId, photos);

                    //tag product to some hash
                    var tagList = bn_HashTag.DivTags(model.Tags);
                    foreach (var tag in tagList)
                    {
                        bnProductTag.Tag(
                            tag,
                            ps_Membership.GetUser().UserId, null);
                    }

                    return RedirectToAction("Detail", new { productId = productId });
                }

                //alert error
                return View(model);
            }

            Session["Photos"] = photos;
            model.ProductPhotos = new List<ps_ProductPhoto>();
            return View(model);
        }

        [Authorize]
        public ActionResult Edit(Guid productId)
        {
            bn_Product bnProduct = new bn_Product();
            pb_Product product = bnProduct.GetById(productId);

            if (product != null)
            {
                bn_Photo bnPhoto = new bn_Photo();
                bn_ProductTag bnProductTag = new bn_ProductTag(productId);
                ps_ProductCreate model = new ps_ProductCreate();

                var photoList = bnPhoto.GetByProductId(productId);
                List<ps_ProductPhoto> photos = new List<ps_ProductPhoto>();
                foreach (var item in photoList)
                {
                    photos.Add(new ps_ProductPhoto {
                        PhotoId = item.PhotoId,
                        PhotoPath = item.ImagePath
                    });
                }

                model.Product = product;
                model.Product.Description = HttpUtility.HtmlDecode(model.Product.Description);
                model.Tags = bnProductTag.GetTagedList();
                model.ProductPhotos = photos;
                Session["Photos"] = new List<ps_ProductPhoto>();
                return View(model);
            }
            else
            {
                //redirect to error page
                return RedirectToAction("Error404", "Error");
            }
        }

        [HttpPost]
        public ActionResult Edit(ps_ProductCreate model)
        {
            if (ModelState.IsValid)
            {
                bn_Product bnProduct = new bn_Product();
                bn_ProductTag bnProductTag = new bn_ProductTag(model.Product.ProductId);

                bnProduct.Update(
                    model.Product.ProductId,
                    model.Product.Name,
                    model.Product.Price,
                    model.Product.Description);

                //photos
                List<ps_ProductPhoto> photos = (List<ps_ProductPhoto>)Session["Photos"];
                Photo_UpdateProductId(
                    model.Product.ProductId,
                    photos);

                //update hashtags 
                //is under construction
                bnProductTag.RemoveAll();
                bnProductTag.TagedToSome(model.Tags, model.Product.UserId);

                return RedirectToAction("Detail", new { productId = model.Product.ProductId });
            }

            model.Product.Description = HttpUtility.HtmlDecode(model.Product.Description);
            return View(model);
        }

        //[Authorize]
        public ActionResult Detail(Guid productId)
        {
            bn_Product bnProduct = new bn_Product();
            var model = bnProduct.GetById(productId);
            bnProduct.IncrViews(model.ProductId);

            if (Request.IsAjaxRequest())
            {
                return PartialView("ProductSumary", model);
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Delete(Guid id)
        {
            bn_Product bnProduct = new bn_Product();
            bnProduct.UpdateStatus(
                id, EProduct_Status.UnAvailable);
            return Redirect("/");
        }

        [Authorize]
        public ActionResult Favourite(Guid productId)
        {
            bn_ProductTag bnProductTag = new bn_ProductTag(productId);

            if (Request.IsAjaxRequest())
            {
                int status = 0;
                if (bnProductTag.IsTag(ps_Membership.GetUser().UserId, ESpecialTag.Favourite.ParseToText())) //tagged
                {

PencilBox/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PbData.Business;
using PbData.Entities;
using PencilBox.Helpers;

namespace PencilBox.Controllers
{
    public class TagController : Controller
    {
        //
        // GET: /Tag/

        public ActionResult p_TagHeader(string tagName)
        {
            bn_HashTag bnHashTag = new bn_HashTag();
            var model = bnHashTag.GetByTagName(tagName);
            bnHashTag.IncrViews(model.HashTagId);

            return View(model);
        }
        public ActionResult p_ProductTags(Guid productId)
        {
            bn_HashTag bnHashTag = new bn_HashTag();
            var model = bnHashTag.GetByProductId(productId);

            return View(model);
        }

        [Authorize]
        public ActionResult Index(Guid? userId)
        {
            if (!userId.HasValue)
                userId = (Guid)ps_Membership.GetUser().UserId;

            bn_HashTag bnHashTag = new bn_HashTag();
            var model = bnHashTag.GetByUserId(
                (Guid)userId, 
                EHashtag_Type.Private);
            
            return View(model);
        }

        [Authorize]
        public ActionResult Add()
        {
            pb_HashTag model = new pb_HashTag();
            model.UserId = ps_Membership.GetUser().UserId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(pb_HashTag model)
        {
            bn_HashTag bnHashTag = new bn_HashTag();
            string iconPath = (string)Session["IconPath"];
            if (iconPath != null)
                model.IconPath = iconPath;
            //Check image
            //if (iconPath == "" || iconPath == null)
            //{
            //    ViewBag.Message = "Phải có ít nhất một hình ảnh.";
            //    return View(model);
            //}

            //Check hashtag
            if (bnHashTag.IsExists(model.TagName))
            {
                ViewBag.Message = "This tag has been create, choose another one, please!";
                return View(model);
            }

            if (ModelState.IsValid)
            {
                bnHashTag.Create(
                    model.UserId,
                    EHashtag_Type.Private,
                    model.TextName,
                    model.TagName,
                    model.Icon,
                    model.Description,
                    model.UserTypes);

                //clear iconpath;
                Session["IconPath"] = null;

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(string tagName)
        {
            bn_HashTag bn_hashTag = new bn_HashTag();
            var model = bn_hashTag.GetByTagName(tagName);

            //clear iconpath;
            Session["IconPath"] = null;

            if (model != null)
                return View(model);
            else
                return View(model);
        }

        [HttpPost]
        public ActionResult Edit(pb_HashTag model)
        {
            bn_HashTag bnHashTag = new bn_HashTag();

            string iconPath = (string)Session["IconPath"];
            if (iconPath == "" || iconPath == null)
                iconPath = model.IconPath;

            if (ModelState.IsValid)
            {
                bnHashTag.Update(
                    model.HashTagId,
                    model.Type,
                    iconPath,
                    model.Description,
                    model.UserTypes);

                //clear iconpath;
                Session["IconPath"] = null;

                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

PencilBox/Views/Product/Detail.cshtml
@model PbData.Entities.pb_Product

@{
    ViewBag.Title = Model.Name;
}

@section featured 
{
    <div class="image-slider" style="padding-left: 5px; padding-right: 5px">
        <div class="content" style="height: 400px; width: 100%;">
            @foreach (var item in Model.pb_Photo.OrderBy(m => m.Status).ToList())
            {
                <img src="~/PencilBox_Data/Images/@item.ImageFixH1()" height="400"
                    class="product-image"/>
            }
        </div>
    </div>

    <div class="content-wrapper">
        <table class="grid" style="margin:4px 0px">
            <tr>
                <td style="font-size:16px; color: white">
                    @*<span class="glyphicon glyphicon-eye-open"></span>*@
                    <span>@Model.Name</span>
                    <span>(mã sản phẩm: @Model.HumanCode)</span>
                </td>

                <td style="width: 120px; text-align: right; padding-right:10px; font-size:16px; color: white; ">
                    <b style="font-weight:bold">@Model.HumanPrice()</b> vnđ</td>

                @if(ps_Membership.IsCurrentUser(Model.UserId))
                {
                    <td style="width: 120px;">
                        <a class="modern-button theme-a"
                            href="https://www.facebook.com/sharer/sharer.php?u=@ps_ServerHelper.Domain/Product/Detail?productId=@Model.ProductId" 
                            target="_blank">Share</a>
                    </td>

                    <td style="width: 80px; padding-left:4px">
                        @Html.ActionLink("Edit", "Edit", "Product", 
                            new { productId = @Model.ProductId }, 
                            new { @class = "modern-button theme-b" })
                    </td>
                    <td style="width: 80px; padding-left:4px">
                        @Html.ActionLink("Delete", "Delete", "Product", 
                            new { id = @Model.ProductId }, 
                            new { @class = "modern-button theme-b" })

                    </td>
                } else
                {
                    <td style="width: 120px;">
                        @Html.ActionLink("Mua Ngay", "New", "Order", 
                            new { productId = @Model.ProductId }, 
                            new { @class = "modern-button theme-a" })
                    </td>

                    <td style="width: 80px; padding-left:4px">
                        @if (ps_Membership.IsAuthenticated() &&
                            Model.IsTag(ps_Membership.GetUser().UserId, 
                            PbData.Business.ESpecialTag.Favourite))
                        {
                            <div style="height:35px; text-align:center" class="theme-b">
                                <a href="#" style="line-height:35px;">
                                    <img src="~/Content/images/tool-Shape-Heart.png" width="35" />
                                </a>
                            </div>
                        }
                        else
                        {
                            
                            <div style="height:35px; text-align:center" class="theme-b">
                                <a href="@Url.Action("Favourite", "Product", new { productId = @Model.ProductId })" style="line-height:35px;" >
                                    <img src="~/Content/images/tool-Heart.png" width="35" />
                                </a>
                            </div>
                        }
                    </td>
                }
            </tr>
        </table>
    </div>
}

<div >
    <div style="display:table; width:100%">
        <div class="sub-main">
            @*<img src="~/PencilBox_Data/Avatars/275867_100000444698747_1555330678_q.jpg" />
            <b style="vertical-align:top">Tư Cuồng</b>*@
            <hgroup class="title">
                <h3>Details (@Model.Views views).</h3></hgroup>
                <p style="color: #282828">@Html.Raw(HttpUtility.HtmlDecode(Model.Description))</p>
        </div>
        <div class="sub-right">
            <hgroup class="title">
                <h3>Tags.</h3></hgroup>
            @Html.Action("p_ProductTags", "Tag", new { productId = Model.ProductId })
        </div>
    </div>

    <div class="border-top" style="display:table; width:100%">
        <div class="sub-main">
            <hgroup class="title">
                <h3>Locations.</h3></hgroup>
            @Html.Action("p_UserLocation", "Location", new { userId = Model.UserId })
        </div>

        <div class="sub-right">
            <hgroup class="title">
                <h3>Contacts.</h3></hgroup>
            @Html.Action("p_UserContact", "Contact", new { userId = Model.UserId })
        </div>
    </div>

    <div class="border-top" style="display:table; width:100%">
        <div class="sub-main">
            <hgroup class="title">
                <h3>Comments.</h3></hgroup>

            <div class="fb-comments" 
                data-href="@ps_ServerHelper.Domain/Product/Detail?productId=@Model.ProductId" 
                data-width="630" 
                data-num-posts="10"></div>
        </div>

        <div class="sub-right">
            <hgroup class="title">
                <h3>...</h3></hgroup>
        </div>
    </div>
</div>



@section headercontent
{
    <link href="~/Content/custom-scrollbar/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/Content/custom-scrollbar/js/minified/jquery.mCustomScrollbar.concat.min.js"></script>

    <script>
        (function ($) {
            $(window).load(function () {

                $(".content").mCustomScrollbar({
                    scrollInertia: 550,
                    horizontalScroll: true,
                    mouseWheelPixels: 116,
                    autoHideScrollbar: true
                });

            });

        })(jQuery);

    </script>
}

PencilBox/Views/Product/Own.cshtml
@model IEnumerable<PbData.Entities.pb_Product>

@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<div id="panel_ProductSearch" class="border-bottom" 
    style="padding-bottom:4px; margin-bottom:6px">

    <div class="input-group">
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                Hôm nay <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="#">Hôm nay</a></li>
                <li><a href="#">Từ hôm qua</a></li>
                <li><a href="#">Trong tuần này</a></li>
                <li><a href="#">Trong tháng này</a></li>
            </ul>
        </div>
        <input type="text" class="form-control">
        <span class="input-group-btn">
            <button type="button" class="btn btn-info">search</button>
        </span>
    </div>

    @*<table class="grid">
        <tr>
            <td style="width:140px">
                <select class="dropDown" style="width:140px; margin-top:-1px">
                    <option value="1">Hôm nay</option>
                    <option value="2">Từ hôm qua</option>
                    <option value="3">Trong tuần này</option>
                    <option value="3">Trong tháng này</option>
                </select>
            </td>
            <td>
                @using (Html.BeginForm("Filter", "Product", FormMethod.Get, new { style="display:inline" }))
                {
                    <input type="text" name="request" value="@ViewBag.FilterRequest"
                        style="width:97%; height:20px; outline:none; padding:4px; border-color:#dadad6; color:black; font-family:'Segoe UI'"
                        placeholder="tìm kiếm" />
                }
            </td>
            <td style="width:120px">
                <a href="#" class="theme-a" 
                    style="display:inline-block; width:120px; height:30px; line-height:30px; text-align:center">Search</a>
            </td>
        </tr>
    </table>*@
</div>

@if (Model.Count() == 0)
{
    <p>Bạn chưa đăng sản phẩm nào. Hãy bắt đầu ngay. ^^</p>
}

@foreach (var item in Model)
{
    if(item.CoverImage != null)
    {
        @Html.Partial("p_ProductView", item)
    }
}

PencilBox/Views/Product/Page.cshtml
@model IEnumerable<PbData.Entities.pb_Product>

@{
    Layout = null;
}

@{string coverImage = "";}
@{int count = 0;}
@foreach (var item in Model)
{
    if (@item.pb_Photo.Count > 0)
    {
        //coverImage = item.CoverImage.ImagePath;
        coverImage = item.CoverImage.ImageFixW1();
        System.Drawing.Image image = System.Drawing.Image.FromFile(Server.MapPath("~/PencilBox_Data/Images/") + coverImage);
    <li>
        <div class="item-inner">
            <a class="cover-block" href="@Url.Action("detail", "product", new { productId = item.ProductId, q = "summary" })">
                <img src="~/PencilBox_Data/Images/@coverImage" 
                    width="230" 
                    height="@((230 * image.Height)/image.Width)" />
            </a>
            <div class="theme-j" style="padding:6px 4px;">
                <b style="float:right; color:#ea1943;">@item.HumanShortPrice()</b>

                <a href="@Url.Action("detail", "product", new { productId = item.ProductId })">@item.DisplayName()</a>
            </div>
            @if (ps_Membership.IsAuthenticated() &&
                item.IsTag(ps_Membership.GetUser().UserId, 
                PbData.Business.ESpecialTag.Favourite))
            {
                <div class="theme-b jd-btn-favourite-sm">
                    <a class="button-favourite" href="@Url.Action("Favourite", "Product", new { productId = @item.ProductId })" class="button-favourite">
                        <img src="~/Content/images/tool-Shape-Heart.png" width="35" />
                    </a>
                </div>
            }
            else
            {
                <div class="theme-b jd-btn-favourite-sm">
                    <a class="button-favourite" href="@Url.Action("Favourite", "Product", new { productId = @item.ProductId })" style="line-height:35px;" >
                        <img src="~/Content/images/tool-Heart.png" width="35" />
                    </a>
                </div>
            }
        </div>
		<div>
		</div>
    </li>
    }
}

PencilBox/Views/Product/ProductSumary.cshtml
@model PbData.Entities.pb_Product
@{
    Layout = null;
}
<div class="jd-sm-left-panel">
    <span id="pb-btn-close" onclick="pb_closeOverlay()"></span>
    <div class="jd-summary-block">
        @{string coverImage = "";}
        @if (@Model.pb_Photo.Count > 0)
        {
            //coverImage = item.CoverImage.ImagePath;
            coverImage = Model.CoverImage.ImageFixH1();
            System.Drawing.Image image = System.Drawing.Image.FromFile(Server.MapPath("~/PencilBox_Data/Images/") + coverImage);
            <div style="text-align: center">
                <a href="@Url.Action("detail", "product", new { productId = Model.ProductId})">
                    <img class="thumb-cover" src="~/PencilBox_Data/Images/@coverImage" />
                </a>
            </div>
        }
        <div class="jd-sm-func-bar">
        <ul>
            <li>
                 <b style="font-weight:bold; font-size: 20.83px; color: #fff">@Model.HumanPrice()</b> VNĐ
            </li>
            @if(ps_Membership.IsCurrentUser(Model.UserId))
            {
                <li style="width: 120px;">
                    <a class="modern-button theme-a"
                        href="https://www.facebook.com/sharer/sharer.php?u=@ps_ServerHelper.Domain/Product/Detail?productId=@Model.ProductId" 
                        target="_blank">Share</a>
                </li>
                <li style="width: 80px; padding-left:4px">
                    @Html.ActionLink("Edit", "Edit", "Product", 
                        new { productId = @Model.ProductId }, 
                        new { @class = "modern-button theme-b" })
                </li>
                <li style="width: 80px; padding-left:4px">
                    @Html.ActionLink("Delete", "Delete", "Product", 
                        new { id = @Model.ProductId }, 
                        new { @class = "modern-button theme-b" })
                </li>
            } 
            else
            {
                <li style="width: 120px;">
                    @Html.ActionLink("Buy", "New", "Order", 
                        new { productId = @Model.ProductId }, 
                        new { @class = "modern-button theme-a" })
                </li>

                <li style="width: 80px; padding-left:4px">
                    @if (ps_Membership.IsAuthenticated() &&
                        Model.IsTag(ps_Membership.GetUser().UserId, 
                        PbData.Business.ESpecialTag.Favourite))
                    {
                        <div style="height:35px; text-align:center" class="theme-b">
                            <a href="#" style="line-height:35px;">
                                <img src="~/Content/images/tool-Shape-Heart.png" width="35" />
                            </a>
                        </div>
                    }
                    else
                    {
                        <div style="height:35px; text-align:center" class="theme-b">
                            <a href="@Url.Action("Favourite", "Product", new { productId = @Model.ProductId })" style="line-height:35px;" >
                                <img src="~/Content/images/tool-Heart.png" width="35" />
                            </a>
                        </div>
                    }
                </li>
            }
        </ul>
        </div>
    </div>
</div>
<div class="jd-sm-right-panel">
    <div class="jd-summary-block">
        <h2>@Model.DisplayName()</h2>
        <p class="jd-product-code">Mã sản phẩm: @Model.HumanCode</p>
        <p class="well well-small jd-product-desc">@Html.Raw(HttpUtility.HtmlDecode(Model.Description))</p>
    </div>

</div>

PencilBox/Views/Product/p_ProductView.cshtml
@model PbData.Entities.pb_Product

@{
    Layout = null;
}

<div style="display:table; width:100%" class="border-bottom">
    <div style="display:inline-block; width:200px; max-height:200px; overflow:hidden">
        <a href="@Url.Action("Detail", "Product", new { productId = Model.ProductId })">
            <img src="@Url.Content("/PencilBox_Data/Images/" + Model.CoverImage.ImageFixW1())" width="200" />
        </a>
    </div>

    <div style="display:inline-block; vertical-align:top; margin-left:10px">
        <b style="font-size:18px">
            <a href="@Url.Action("Detail", "Product", new { productId = @Model.ProductId })">
                @Model.Name
            </a>
        </b><br />

        <table class="grid">
            <tr>
                <td style="width:80px"><span>Price</span></td>
                <td><b>@Model.Price</b></td>
            </tr>
            <tr>
                <td><span>Favourite</span></td>
                <td><b>1250</b></td>
            </tr>
        </table>
    </div>
</div>