PencilBox/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PbData.Business;
using PbData.Entities;
using PencilBox.Helpers;
using PencilBox.Models;

namespace PencilBox.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult p_UserContact(Guid userId)
        {
            bn_UserContact bnUserContact = new bn_UserContact();
            bn_UserProfile bnUserProfile = new bn_UserProfile();
            ps_UserContact model = new ps_UserContact();

            model.UserProfile = bnUserProfile.GetById(userId);
            model.Contacts = bnUserContact.GetByUserId(userId);

            return View(model);
        }

        public ActionResult Index(Guid? userId)
        {
            if (!userId.HasValue)
                userId = ps_Membership.GetUser().UserId;

            bn_UserContact bnUserContact = new bn_UserContact();
            bn_UserProfile bnUserProfile = new bn_UserProfile();
            ps_UserContact model = new ps_UserContact();

            model.Contacts = bnUserContact.GetByUserId((Guid)userId);
            model.UserProfile = bnUserProfile.GetById((Guid)userId);

            return View(model);
        }

        [Authorize]
        public ActionResult Add()
        {
            bn_ContactType bnContactType = new bn_ContactType();
            ps_ContactType model = new ps_ContactType();

            model.ContactTypes = bnContactType.GetAll();

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(ps_ContactType model)
        {
            if (ModelState.IsValid)
            {
                bn_UserContact bnUserContact = new bn_UserContact();

                var userContactId = bnUserContact.Create(
                    ps_Membership.GetUser().UserId,
                    model.UserContact.ContactTypeId,
                    model.UserContact.ContactName);

                return RedirectToAction("Index", "User");
            }
            return View();
        }

        public ActionResult Delete(Guid userContactId)
        {
            bn_UserContact bnUserContact = new bn_UserContact();
            var re = bnUserContact.Delete(userContactId);

            return RedirectToAction("Index", "User");
        }
    }
}

PencilBox/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PencilBox.Helpers;
using PbData.Business;
using PbData.Entities;

namespace PencilBox.Controllers
{
    public class LocationController : Controller
    {
        public ActionResult p_UserLocation(Guid userId)
        {
            bn_Location bnLocation = new bn_Location();
            var model = bnLocation.GetByUserId((Guid)userId);

            if (model.Count > 0)
                return View(model);
            else
                return null;
        }

        public ActionResult Index(Guid? userId)
        {
            if (!userId.HasValue)
                userId = ps_Membership.GetUser().UserId;

            bn_Location bnLocation = new bn_Location();
            var model = bnLocation.GetByUserId((Guid)userId);
            ViewBag.UserId = userId;

            return View(model);
        }

        [Authorize]
        public ActionResult New()
        {
            pb_Location model = new pb_Location();
            model.UserId = ps_Membership.GetUser().UserId;

            return View(model);
        }

        [HttpPost]
        public ActionResult New(pb_Location model)
        {
            if (ModelState.IsValid && model.Address != null)
            {
                bn_Location bnLocation = new bn_Location();
                var re = bnLocation.Create(
                    model.UserId,
                    model.Latitude,
                    model.Longitude,
                    model.Address);

                if (re != Guid.Empty)
                {
                    return RedirectToAction("Index", "User");
                }

                //return fail.
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Edit(Guid locationId)
        {
            bn_Location bnLocation = new bn_Location();
            var model = bnLocation.GetById(locationId);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(pb_Location model)
        {
            if (ModelState.IsValid && model.Address != null)
            {
                bn_Location bnLocation = new bn_Location();
                var re = bnLocation.Update(
                    model.LocationId,
                    model.Latitude,
                    model.Longitude,
                    model.Address);

                if (re >= 0)
                {
                    return RedirectToAction("Index", "User");
                }

                //return fail.
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Delete(Guid locationId)
        {
            bn_Location bnLocation = new bn_Location();
            var re = bnLocation.Delete(locationId);

            if (re < 0)
            {
                ViewBag.MessError = "";
            }
            return RedirectToAction("Index", "User");
        }
    }
}

PencilBox/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PbData.Business;
using PbData.Extensions;

namespace PencilBox.Controllers
{
    public class TestController : Controller
    {
        //
        // GET: /Test/

        public ActionResult Index()
        {
            return View();
        }

        public string GetEnumValue()
        {
            return ESpecialTag.Discount.ParseToText();
        }

        public ActionResult Tipsy()
        {
            return View();
        }

    }
}

PencilBox/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PbData.Business;
using PbData.Entities;
using PbData.Extensions;
using PencilBox.Helpers;

namespace PencilBox.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/
        public ActionResult p_UserInfomation(Guid userId)
        {
            var model = ps_Membership.GetUser();

            return View(model);
        }

        [Authorize]
        public ActionResult Index()
        {
            var model = ps_Membership.GetUser();

            return View(model);
        }

        [Authorize]
        public ActionResult Edit(Guid? userId)
        {
            if (!userId.HasValue)
                userId = ps_Membership.GetUser().UserId;

            bn_UserProfile bnUserProfile = new bn_UserProfile();
            pb_UserProfile model = new pb_UserProfile();

            model = bnUserProfile.GetById((Guid)userId);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(pb_UserProfile model)
        {
            if (ModelState.IsValid)
            {
                bn_UserProfile bnUserProfile = new bn_UserProfile();
                var re = bnUserProfile.Update(
                    ps_Membership.GetUser().UserId,
                    model.FirstName,
                    model.LastName,
                    model.DateOfBirth);

                if (re >= 0)
                {
                    return RedirectToAction("Index", "User");
                }
                else
                {
                    //can't udpate
                }
            }

            return View(model);
        }

        [Authorize]
        public ActionResult Favourite()
        {
            bn_Product bnProduct = new bn_Product();
            var model = bnProduct.GetByUserAndTagName(
                ps_Membership.GetUser().UserId,
                ESpecialTag.Favourite.ParseToText());

            return View(model);
        }
    }
}

PencilBox/Views/User/Edit.cshtml
@model PbData.Entities.pb_UserProfile

@{
    ViewBag.Title = "Chỉnh sửa thông tin";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td class="left-element">First Name</td>
            <td>@Html.TextBoxFor(m => m.FirstName)</td>
        </tr>
        <tr>
            <td class="left-element">Last Name</td>
            <td>@Html.TextBoxFor(m=>m.LastName)</td>
        </tr>
        <tr>
            <td class="left-element">Date of birth</td>
            <td>@Html.TextBoxFor(m => m.DateOfBirth, new { id = "datepicker_dateofbirth" })</td>
        </tr>
        <tr>
            <td class="left-element">Avatar</td>
            <td><input type="file" name="avatar_attachment" id="upload_avatar" /></td>
        </tr>
        <tr>
            <td class="left-element"></td>
            <td>
                @Html.HiddenFor(m => m.Avatar)
                <input type="submit" class="modern-button theme-a width120" />
                <a href="@Url.Action("Index", "User")" class="modern-button theme-b width80">Cancel</a>
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#upload_avatar").kendoUpload({
            async: {
                saveUrl: "/Upload/UploadAvatar?userId=@Model.UserId",
                autoUpload: true
            }
        });

        $("#datepicker_dateofbirth").kendoDatePicker({
            format: "dd/MM/yyyy"
        });
    });
</script>

PencilBox/Views/User/Favourite.cshtml
@model IEnumerable<PbData.Entities.pb_Product>

@{
    ViewBag.Title = "Sản phẩm yêu thích";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

@if (Model.Count() == 0)
{
    <p>Bạn chưa yêu thích sản phầm nào, hãy lướt qua một vòng và tìm món hàng bạn yêu thích.</p>
}

@foreach (var item in Model)
{
    @Html.Partial("~/Views/Product/p_ProductView.cshtml", item)
}

PencilBox/Views/User/Index.cshtml
@model PbData.Entities.pb_UserProfile

@{
    ViewBag.Title = "Thông tin người dùng";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div>
    <div>
        <div style="float:right; display:inline-block">
            <a href="@Url.Action("edit", "user")" >
                <img src="~/Content/images/base-edit-light.png" width="30"
                    onmouseover="this.src='/Content/images/base-edit-dark.png'"
                    onmouseout="this.src='/Content/images/base-edit-light.png'" /></a>
        </div>

        <hgroup class="title">
            <h2>@ViewBag.Title.</h2>
        </hgroup>
    </div>

    @Html.Action("p_UserInfomation", "User", new { userId = Model.UserId })
</div>


<div class="border-top">
    <div>
        <div style="float:right; display:inline-block">
            <a href="@Url.Action("add", "contact")" >
                <img src="~/Content/images/base-add-light.png" width="30"
                    onmouseover="this.src='/Content/images/base-add-dark.png'"
                    onmouseout="this.src='/Content/images/base-add-light.png'" /></a>
        </div>

        <hgroup class="title">
            <h2>Liên lạc.</h2>
        </hgroup>
    </div>

    @Html.Action("p_UserContact", "Contact", new { userId = Model.UserId })
</div>

<div class="border-top">
    <div>
        <div style="float:right; display:inline-block">
            <a href="@Url.Action("new", "location")" >
                <img src="~/Content/images/base-add-light.png" width="30"
                    onmouseover="this.src='/Content/images/base-add-dark.png'"
                    onmouseout="this.src='/Content/images/base-add-light.png'" /></a>
        </div>

        <hgroup class="title">
            <h2>Địa điểm.</h2>
        </hgroup>
    </div>

    @Html.Action("p_UserLocation", "Location", new { userId = Model.UserId })
</div>

PencilBox/Views/User/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<p>Chuyện tình dưới mưa</p>

@*@section rightpanel
{
    <div class="metro-panel">
        <a href="/User?userId=@Model">Thông Tin</a>
        <a href="/Location?userId=@Model">Địa chỉ</a>
        <a href="/Place/ByUser?userId=@Model">Địa điểm đã tạo</a>
        <a href="/Arrived?userId=@Model">Địa điểm đã tới</a>
    </div>
}*@

PencilBox/Views/User/p_UserInfomation.cshtml
@model PbData.Entities.pb_UserProfile

@{
    Layout = null;
}

<table>
    <tr>
        <td class="left-element">Full Name</td>
        <td><b>@Model.FullName</b></td>
    </tr>
    <tr>
        <td class="left-element">Email</td>
        <td><b>@Model.UserName</b></td>
    </tr>
    <tr>
        <td class="left-element">Birthday</td>
        <td><b>@Model.DateOfBirth.GetValueOrDefault().ToShortDateString()</b></td>
    </tr>
</table>